spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata?serverTimezone=CST&characterEncoding=utf-8
    username: root
    password: li545426
mybatis:
  mapper-locations: classpath:mapper/*.xml